# Generated by Django 5.2.5 on 2025-11-09 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_customer_education_and_more'),
        ('storefront', '0005_productreview_is_anonymous_deliveryservicereview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.CharField(choices=[('not_received', 'I did not receive my item'), ('not_satisfied', "I received item but I'm not satisfied")], max_length=20)),
                ('refund_reason', models.CharField(choices=[('defective', 'Defective/Damaged item'), ('wrong_item', 'Wrong item received'), ('not_as_described', 'Item not as described'), ('quality_issue', 'Quality issue'), ('size_fit', 'Size/Fit issue'), ('changed_mind', 'Changed my mind'), ('duplicate', 'Duplicate order'), ('other', 'Other')], max_length=50)),
                ('additional_comments', models.TextField(blank=True)),
                ('refund_method', models.CharField(choices=[('credit_card', 'Refund via credit card'), ('original_payment', 'Refund to original payment method')], default='credit_card', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('accepted_policy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='adminpanel.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='returns/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.orderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='storefront.returnrequest')),
            ],
            options={
                'unique_together': {('return_request', 'order_item')},
            },
        ),
    ]
