# Generated by Django 5.2.7 on 2025-10-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_customer_education_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='quantity_on_hand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='reorder_threshold',
            new_name='reorder_quantity',
        ),
    ]
