# Generated by Django 5.2.7 on 2025-10-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_on_hand',
            field=models.IntegerField(),
        ),
    ]
