# Generated by Django 5.2.5 on 2025-10-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_alter_product_quantity_on_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='When unchecked, this product will be hidden from the customer storefront.'),
        ),
    ]
