# Generated by Django 5.2.5 on 2025-11-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(choices=[('standard', 'Standard Shipping (Free)'), ('express', 'Express Shipping (+$4.99)'), ('overnight', 'Overnight Shipping (+$12.99)')], default='standard', help_text='Shipping speed selected by customer', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('paynow', 'PayNow')], default='card', help_text='Payment method used for this order', max_length=20),
        ),
    ]
