# Generated by Django 5.2.5 on 2025-11-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_chat_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Banner title for identification', max_length=255)),
                ('image', models.ImageField(help_text='Banner image (recommended: 1920x500px)', upload_to='banners/')),
                ('link', models.URLField(blank=True, help_text='Optional URL to redirect when banner is clicked', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers show first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this banner on storefront')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
