# Generated by Django 5.2.7 on 2025-11-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='preferred_category',
            field=models.CharField(choices=[('Automotive', 'Automotive'), ('Beauty & Personal Care', 'Beauty & Personal Care'), ('Books', 'Books'), ('Electronics', 'Electronics'), ('Fashion - Men', 'Fashion - Men'), ('Fashion - Women', 'Fashion - Women'), ('Groceries & Gourmet', 'Groceries & Gourmet'), ('Health', 'Health'), ('Home & Kitchen', 'Home & Kitchen'), ('Pet Supplies', 'Pet Supplies'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Toys & Games', 'Toys & Games')], max_length=100),
        ),
    ]
