# Generated by Django 5.2.5 on 2025-11-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_update_preferred_category_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_sold',
            field=models.IntegerField(default=0, help_text='Pre-populated quantity sold from transaction data'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='occupation',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Education', 'Education'), ('Sales', 'Sales'), ('Service', 'Service'), ('Skilled Trades', 'Skilled Trades'), ('Tech', 'Tech')], max_length=50),
        ),
    ]
