# Generated by Django 5.2.7 on 2025-11-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_product_quantity_sold_alter_customer_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Action Figures', 'Action Figures'), ('Aquatic', 'Aquatic'), ('Bedding', 'Bedding'), ('Beverages', 'Beverages'), ('Board Games', 'Board Games'), ('Bottoms', 'Bottoms'), ('Breakfast', 'Breakfast'), ('Building Sets', 'Building Sets'), ('Cameras', 'Cameras'), ('Camping & Hiking', 'Camping & Hiking'), ('Car Care', 'Car Care'), ('Cat', 'Cat'), ('Children', 'Children'), ('Comics & Manga', 'Comics & Manga'), ('Cookware', 'Cookware'), ('Cycling', 'Cycling'), ('Dog', 'Dog'), ('Dresses', 'Dresses'), ('Exterior Accessories', 'Exterior Accessories'), ('Fiction', 'Fiction'), ('First Aid', 'First Aid'), ('Fitness Equipment', 'Fitness Equipment'), ('Footwear', 'Footwear'), ('Fragrances', 'Fragrances'), ('Grooming Tools', 'Grooming Tools'), ('Hair Care', 'Hair Care'), ('Handbags', 'Handbags'), ('Headphones', 'Headphones'), ('Health Foods', 'Health Foods'), ('Home Decor', 'Home Decor'), ('Interior Accessories', 'Interior Accessories'), ('Laptops', 'Laptops'), ('Makeup', 'Makeup'), ('Medical Devices', 'Medical Devices'), ('Monitors', 'Monitors'), ('Non-Fiction', 'Non-fiction'), ('Oils & Fluids', 'Oils & Fluids'), ('Outerwear', 'Outerwear'), ('Pantry Staples', 'Pantry Staples'), ('Personal Care', 'Personal Care'), ('Printers', 'Printers'), ('Puzzles', 'Puzzles'), ('STEM Toys', 'STEM Toys'), ('Skincare', 'Skincare'), ('Small Appliances', 'Small Appliances'), ('Small Pets', 'Small Pets'), ('Smart Home', 'Smart Home'), ('Smartphones', 'Smartphones'), ('Smartwatches', 'Smartwatches'), ('Snacks', 'Snacks'), ('Storage & Organization', 'Storage & Organization'), ('Supplements', 'Supplements'), ('Tablets', 'Tablets'), ('Team Sports', 'Team Sports'), ('Textbooks', 'Textbooks'), ('Tools & Equipment', 'Tools & Equipment'), ('Tops', 'Tops'), ('Vacuum & Cleaning', 'Vacuum & Cleaning'), ('Yoga & Wellness', 'Yoga & Wellness')], max_length=100),
        ),
    ]
