"""
Django settings for auroramart_project project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Try to import decouple, but make it optional
try:
    from decouple import config, Csv, AutoConfig
    config = AutoConfig(search_path=Path(__file__).resolve().parent.parent)
    DECOUPLE_AVAILABLE = True
except ImportError:
    # Fallback if decouple is not installed
    def config(key, default=None, cast=None):
        value = os.environ.get(key, default)
        if cast and value != default:
            try:
                return cast(value)
            except (ValueError, TypeError):
                return default
        return value
    DECOUPLE_AVAILABLE = False
    print("Note: python-decouple not installed. Using environment variables only.")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)bu5tt-ysrbs_+&fg&u0$0+yg1#jr9*u)l7$#m+(h2po(p5^d='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'adminpanel',
    'storefront',
]

# Add social_django if available (for Google OAuth)
try:
    import social_django
    INSTALLED_APPS.append('social_django')
    SOCIAL_AUTH_ENABLED = True
except ImportError:
    SOCIAL_AUTH_ENABLED = False
    print("Note: social_django not installed. Google OAuth will not be available.")
    print("Install it with: pip install social-auth-app-django")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Add social_django middleware if available
if SOCIAL_AUTH_ENABLED:
    MIDDLEWARE.append('social_django.middleware.SocialAuthExceptionMiddleware')

ROOT_URLCONF = 'auroramart_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'storefront.context_processors.categories',
            ],
        },
    },
]

WSGI_APPLICATION = 'auroramart_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Singapore'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default Django authentication
]

# Social Auth Settings (Google OAuth)
# Read from .env file or environment variables
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config('GOOGLE_OAUTH2_CLIENT_ID', default='')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config('GOOGLE_OAUTH2_CLIENT_SECRET', default='')

# Always register the backend if social_django is installed (needed for URLs to work)
# But only configure it properly if credentials are provided
if SOCIAL_AUTH_ENABLED:
    # Register backend so URLs work (even without credentials)
    if 'social_core.backends.google.GoogleOAuth2' not in AUTHENTICATION_BACKENDS:
        AUTHENTICATION_BACKENDS.insert(0, 'social_core.backends.google.GoogleOAuth2')
    
    # Only configure fully if credentials are provided
    if SOCIAL_AUTH_GOOGLE_OAUTH2_KEY and SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET:
        # Note: You need to configure these with your Google OAuth credentials
        # Get them from: https://console.cloud.google.com/apis/credentials
        # Add authorized redirect URI: http://127.0.0.1:8000/oauth/complete/google-oauth2/
        
        SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
            'https://www.googleapis.com/auth/userinfo.email',
            'https://www.googleapis.com/auth/userinfo.profile',
        ]
        
        # Social Auth Pipeline with custom step to create Customer profile
        SOCIAL_AUTH_PIPELINE = (
            'social_core.pipeline.social_auth.social_details',
            'social_core.pipeline.social_auth.social_uid',
            'social_core.pipeline.social_auth.auth_allowed',
            'social_core.pipeline.social_auth.social_user',
            'social_core.pipeline.user.get_username',
            'social_core.pipeline.user.create_user',
            'social_core.pipeline.social_auth.associate_user',
            'social_core.pipeline.social_auth.load_extra_data',
            'social_core.pipeline.user.user_details',
            'storefront.pipeline.create_customer_profile',  # Custom pipeline to create Customer
        )
        print("✓ Google OAuth backend configured with credentials")
    else:
        print("Warning: Google OAuth credentials not set. Set GOOGLE_OAUTH2_CLIENT_ID and GOOGLE_OAUTH2_CLIENT_SECRET environment variables.")
        print("Google OAuth buttons will appear but authentication will fail until credentials are configured.")
        SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = []
        SOCIAL_AUTH_PIPELINE = (
            'social_core.pipeline.social_auth.social_details',
            'social_core.pipeline.social_auth.social_uid',
            'social_core.pipeline.social_auth.auth_allowed',
            'social_core.pipeline.social_auth.social_user',
            'social_core.pipeline.user.get_username',
            'social_core.pipeline.user.create_user',
            'social_core.pipeline.social_auth.associate_user',
            'social_core.pipeline.social_auth.load_extra_data',
            'social_core.pipeline.user.user_details',
            'storefront.pipeline.create_customer_profile',
        )

# Login URLs
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'homepage'
LOGOUT_REDIRECT_URL = 'homepage'

# Email Configuration (for password reset)
# Read email settings from .env file or environment variables
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@auroramart.com')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Use SMTP if credentials are provided, otherwise use console backend for development
if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    print(f"Email configured: Using SMTP ({EMAIL_HOST})")
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    print("Email not configured: Emails will be printed to console.")
    print("To enable email sending, add these to your .env file:")
    print("  EMAIL_HOST=smtp.gmail.com")
    print("  EMAIL_PORT=587")
    print("  EMAIL_USE_TLS=True")
    print("  EMAIL_HOST_USER=your-email@gmail.com")
    print("  EMAIL_HOST_PASSWORD=your-app-password")
    print("  DEFAULT_FROM_EMAIL=noreply@auroramart.com")

# Social Auth Redirect (custom handling in views)
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/oauth-redirect/'
SOCIAL_AUTH_NEW_USER_REDIRECT_URL = '/oauth-redirect/'  # Will check and show modal if needed